package org.sigpep.web.service;

import javax.jws.WebMethod;
import javax.jws.WebService;
import java.util.HashSet;
import java.util.HashMap;

/**
 * Created by IntelliJ IDEA.<br/>
 * User: mmueller<br/>
 * Date: 25-Feb-2008<br/>
 * Time: 17:32:23<br/>
 */

@WebService
public interface SigPepQueryService {


    /**
     * Returns the peptides emitted by a set of proteins when digested with a set of proteaseFilter.
     *
     * @param ncbiTaxonId       the NCBI taxon ID identifying the species
     * @param proteinAccessions the protein accessions
     * @param proteaseName     the names of the proteaseFilter generating the peptides
     * @return a map of protein accessions and peptide sequences
     */
    @WebMethod
    HashMap<String, HashSet<String>> getPeptidesForProteinSet(int ncbiTaxonId, HashSet<String> proteinAccessions, String... proteaseName);

    /**
     * Returns the signature peptides emitted by a protein when digested with a protease.
     *
     * @param ncbiTaxonId      the NCBI taxon ID identifying the species
     * @param proteinAccession the accession of the protein
     * @param proteaseName     the protease generating the peptides
     * @return a set of peptide sequences
     */
    @WebMethod
    HashSet<String> getPeptidesForProtein(int ncbiTaxonId, String proteinAccession, String... proteaseName);

    /**
     * Returns the peptides emitted by a protein when digested with a protease.
     *
     * @param ncbiTaxonId      the NCBI taxon ID identifying the species
     * @param proteinAccession the accession of the protein
     * @param proteaseName     the protease generating the peptides
     * @return a set of peptide sequences
     */
    @WebMethod
    HashSet<String> getSignaturePeptidesForProtein(int ncbiTaxonId, String proteinAccession, String... proteaseName);


    /**
     * Returns the signature peptides emitted by a set of proteins when digested with a set of proteaseFilter.
     *
     * @param ncbiTaxonId       the NCBI taxon ID identifying the species
     * @param proteinAccessions the protein accessions
     * @param proteaseName     the names of the proteaseFilter generating the peptides
     * @return a map of protein accessions and peptide sequences
     */
    @WebMethod
    HashMap<String, HashSet<String>> getSignaturePeptidesForProteinSet(int ncbiTaxonId, HashSet<String> proteinAccessions, String... proteaseName);

    /**
     * Returns the product ions discriminating a target peptide from the background peptides
     * generated by a protease.
     *
     * @param peptide                        the target peptide
     * @param postTranslationalModifications the post translational modifications to take into account
     * @param proteaseName                   the name(s) of the peptide generating protease(s)
     * @return a map of product ion names and masses in Da
     */
    HashMap<String, Double> getSignatureTransitionForPeptideWithPTM(String peptide, HashSet<String> postTranslationalModifications, String... proteaseName);

    /**
     * Returns the product ions discriminating a target peptide from the background peptides
     * generated by a protease.
     *
     * @param peptide                        the target peptide
     * @param proteaseName                   the name(s) of the peptide generating protease(s)
     * @return a map of product ion names and masses in Da
     */
    HashMap<String, Double> getSignatureTransitionForPeptide(String peptide, String... proteaseName);

    @WebMethod
    String sayHello(String name);

}
